# Generated by Django 4.2.4 on 2023-08-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='英文姓名')),
                ('email', models.EmailField(max_length=32, verbose_name='電郵')),
                ('password', models.CharField(max_length=8, verbose_name='密碼')),
            ],
        ),
    ]
