# Generated by Django 4.2.4 on 2023-08-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workwaveapp', '0003_alter_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staffname', models.CharField(max_length=50, verbose_name='英文姓名')),
                ('Staffemail', models.EmailField(max_length=32, unique=True, verbose_name='電郵')),
                ('OT_start', models.DateTimeField(verbose_name='OT開始時間')),
                ('OT_end', models.DateTimeField(verbose_name='OT完結時間')),
                ('TotalOTHour', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='OT總時數')),
                ('ApprovedTotalOTHour', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='OT總時數')),
                ('AccumuatedTotalOTHour', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='OT總時數')),
                ('ApproverList', models.CharField(max_length=50, verbose_name='Approver姓名')),
                ('ApproverEmail', models.EmailField(max_length=32, unique=True, verbose_name='Approver電郵')),
                ('ApprovalStatus', models.CharField(max_length=32, unique=True, verbose_name='Approval Status')),
                ('OT_reason', models.CharField(max_length=200, verbose_name='OT原因')),
                ('Remark', models.CharField(max_length=200, verbose_name='Remark')),
                ('Hv_lunch', models.SmallIntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2, verbose_name='有午餐?')),
                ('Hv_dinner', models.SmallIntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2, verbose_name='有晚餐?')),
            ],
        ),
        migrations.AddField(
            model_name='userregistration',
            name='isApprover',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2, verbose_name='是Approver嗎?'),
        ),
    ]
