# Generated by Django 4.2.4 on 2023-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workwaveapp', '0007_alter_addcl_approverlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcl',
            name='AccumuatedTotalOTHour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OT總時數'),
        ),
        migrations.AlterField(
            model_name='addcl',
            name='ApprovalStatus',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='addcl',
            name='ApprovedTotalOTHour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OT總時數'),
        ),
        migrations.AlterField(
            model_name='addcl',
            name='ApproverEmail',
            field=models.EmailField(blank=True, max_length=32, null=True, unique=True, verbose_name='Approver電郵'),
        ),
    ]
