# Generated by Django 4.2.4 on 2023-09-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workwaveapp', '0010_alter_addcl_approvalstatus_alter_addcl_approveremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcl',
            name='StaffID',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='ID'),
        ),
    ]
