# Generated by Django 4.2.4 on 2023-09-14 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workwaveapp', '0011_addcl_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcl',
            name='TotalOTHour',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='OT總時數'),
        ),
        migrations.CreateModel(
            name='UseCL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CL_start', models.DateTimeField(verbose_name='CL開始時間')),
                ('CL_end', models.DateTimeField(verbose_name='CL完結時間')),
                ('TotalCLHour', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='CL總時數')),
                ('AccumuatedTotalOTHour', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OT總時數')),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='workwaveapp.userregistration', verbose_name='Staff ID')),
                ('Staffemail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='workwaveapp.userregistration', to_field='email', verbose_name='Staff email')),
                ('Staffname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='workwaveapp.userregistration', to_field='name', verbose_name='Staff name')),
            ],
        ),
    ]
